### PR TITLE
REL: Release v0.4.0

### PR DESCRIPTION
**Pull request by davidastephens**
Update to v0.4.0.

### CODE REVIEW

**Comment by jreback** [comment]
@femtotrader

**Comment by mariusvniekerk** [comment]
@jakirkham merge this one?

**Comment by mariusvniekerk** [comment]
We may want to add a constraint on a minimum pandas version (probably >=0.20 ?)

**Comment by jakirkham** [comment]
So I think you guys now have permissions. Please let me know if that is not the case.

**Pull request merged**
